New variables
Ouranosinc/miranda pull request #199
Opened 2024-10-08 18:06 UTC by aslibese

### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [ ] CHANGELOG.rst has been updated (with summary of main changes).
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

Added two new variables tos and sicons to .json 

### Does this PR introduce a breaking change?

No, test done

### Other information:

2024-10-08 18:39 UTC, Zeitsperre commented on AUTHORS.rst
> +* Asli Bese <bese.asli@ouranos.ca> `@aslibese <https://github.com/aslibese>`_
FYI, UTF-8 characters are acceptable here.

2024-10-08 19:25 UTC, tlogan2000 requested changes

2024-10-08 19:25 UTC, tlogan2000 commented on src/miranda/convert/data/ecmwf_cf_attrs.json
> +      "units": "1"
```suggestion
      "units": "%"
```
Maybe double check but I think the CMIP6 data is a % unit.  I'm pretty sure that miranda/xclim will convert "1" to "%" automatically

2024-10-08 19:30 UTC, Zeitsperre commented
@tlogan2000 Once the PR is ready, feel free to use your ultimate admin powers to merge while bypassing the license check. That check will always fail until I find a moment to split the offending modules out.

2024-10-08 20:23 UTC, tlogan2000 approved these changes
I think this looks good.

2024-10-09 17:00 UTC, tlogan2000 requested changes
I will relook at a couple of things this pm in the end.  I'm confused about something

2024-10-22 16:09 UTC, tlogan2000 approved these changes

2025-03-06 21:01 UTC, closed without merging